### ISSUE TITLE
Add automatic deploy to workflow

### ISSUE THREAD

**Issue by M0673N** [bvoytash/Crypto_Analyzator#10]
Add another job to the workflow that automatically deploys the project to Render if the first job is successful. 
- Medium priority

**Comment by M0673N** [comment]
[deploy.txt](https://github.com/user-attachments/files/18231340/deploy.txt)
Example job. Requires the setup of 2 secret variables for the render webhook and api.

**Comment by bvoytash** [comment]
ok
